policies:
queries:
agent_options:
  path: ./lib/agent-options.yml
controls: # This cannot be set here and in no-team.yml
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Fleet
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"