policies:
queries:
agent_options:
  path: ./lib/agent-options.yml
controls: # This cannot be set here and in no-team.yml
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Mario
  webhook_settings:
    activities_webhook:
        enable_activities_webhook: true
        destination_url: https://example.com
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"